# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Tree
version:      3.20
version_from: lib/HTML/Tree.pm
installdirs:  site
requires:
    HTML::Parser:                  2.19
    HTML::Tagset:                  3.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
